import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  FileText, 
  PlusCircle, 
  QrCode,
  X,
  Clock,
  Download,
  Upload,
  PieChart,
  Activity,
  Sparkles,
  ShieldAlert
} from 'lucide-react';
import axios from 'axios';
import { QRCodeSVG } from 'qrcode.react';
import Sidebar from '../components/Sidebar';
import Navbar from '../components/Navbar';

const PatientDashboard = () => {
  const navigate = useNavigate();
  const [user, setUser] = useState(JSON.parse(localStorage.getItem('user')) || {});
  const [profile, setProfile] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [records, setRecords] = useState([]);
  const [showSummaryModal, setShowSummaryModal] = useState(false);
  const [selectedRecord, setSelectedRecord] = useState(null);
  const [isSummarizing, setIsSummarizing] = useState(false);

  useEffect(() => {
    const fetchProfileData = async () => {
      try {
        const token = localStorage.getItem('token');
        const [profileRes, recordsRes] = await Promise.all([
          axios.get('http://localhost:5000/api/patient/profile', {
            headers: { Authorization: `Bearer ${token}` }
          }),
          axios.get('http://localhost:5000/api/patient/records', {
            headers: { Authorization: `Bearer ${token}` }
          })
        ]);
        setProfile(profileRes.data);
        setRecords(recordsRes.data);
      } catch (err) {
        if (err.response?.status === 401) {
          localStorage.clear();
          navigate('/login');
        }
      } finally {
        setIsLoading(false);
      }
    };

    fetchProfileData();
  }, [navigate]);

  const handleSummarize = async (record) => {
    setSelectedRecord(record);
    setIsSummarizing(true);
    // Simulate AI Processing
    setTimeout(() => {
      setIsSummarizing(false);
    }, 2500);
  };


  const handleLogout = () => {
    localStorage.clear();
    navigate('/login');
  };

  if (isLoading) {
    return (
      <div className="loading-screen" style={{ background: 'var(--bg-body)', color: 'var(--primary)' }}>
        <Activity size={48} className="animate-pulse" />
        <p style={{ marginTop: '1rem' }}>Loading CareConnect Dashboard...</p>
      </div>
    );
  }

  return (
    <div className="dashboard-container" style={{ background: 'var(--bg-body)' }}>
      <Sidebar handleLogout={handleLogout} />

      <main className="main-content" style={{ padding: '0 0 3rem 0', maxWidth: '100%', margin: '0' }}>
        <Navbar userProfile={profile} />

        <div style={{ padding: '0 4rem' }}>
          <div className="section-title" style={{ marginBottom: '1.5rem' }}>
            <h2 style={{ fontSize: '1.5rem', color: 'var(--text-primary)' }}>Patient Dashboard</h2>
          </div>

          {/* AI Banner */}
          <div className="ai-banner" style={{ marginBottom: '2.5rem' }}>
            <div style={{ zIndex: '1', maxWidth: '60%' }}>
              <h1 style={{ fontSize: '2.5rem', marginBottom: '1rem', color: 'white' }}>AI Health Summary</h1>
              <p style={{ fontSize: '1rem', opacity: '0.9', marginBottom: '2rem', lineHeight: '1.6' }}>
                Your health records have been analyzed. View your personalized summary and health insights generated by our AI engine.
              </p>
              <div style={{ display: 'flex', gap: '1.25rem' }}>
                <button 
                  onClick={() => {
                    setSelectedRecord({ title: 'Full Health Profile', category: 'Holistic Summary' });
                    setIsSummarizing(true);
                    setTimeout(() => setIsSummarizing(false), 2000);
                  }}
                  className="btn" 
                  style={{ 
                    background: 'white', 
                    color: 'var(--primary)', 
                    padding: '0.875rem 2rem',
                    boxShadow: '0 10px 20px rgba(0,0,0,0.1)',
                    fontWeight: '800'
                  }}
                >
                  <Activity size={18} />
                  Complete Summary
                </button>
                <button 
                  onClick={() => setShowSummaryModal(true)}
                  className="btn" 
                  style={{ 
                    background: 'rgba(255,255,255,0.15)', 
                    color: 'white', 
                    border: '1px solid rgba(255,255,255,0.3)',
                    padding: '0.875rem 2rem',
                    backdropFilter: 'blur(10px)',
                    fontWeight: '700'
                  }}
                >
                  <FileText size={18} />
                  Specific Report Summary
                </button>
              </div>
            </div>
            <div style={{ 
              position: 'absolute', 
              right: '-2rem', 
              bottom: '0', 
              width: '450px',
              height: '100%',
              display: 'flex',
              alignItems: 'flex-end',
              justifyContent: 'center',
              zIndex: '1',
              maskImage: 'linear-gradient(to right, transparent, black 25%)',
              WebkitMaskImage: 'linear-gradient(to left, black 60%, transparent 100%)'
            }}>
              <img 
                src="/doctor_banner_realistic.png" 
                alt="AI Doctor" 
                style={{ 
                  height: '120%', 
                  width: 'auto', 
                  objectFit: 'contain',
                  filter: 'drop-shadow(0 20px 40px rgba(0,0,0,0.1))'
                }}
              />
            </div>
          </div>

          {/* Action Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '2rem' }}>
            <div className="dashboard-card" style={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: '2rem', 
              cursor: 'pointer',
              background: 'var(--bg-surface)'
            }} onClick={() => navigate('/upload-record')}>
              <div style={{ 
                width: '80px', 
                height: '80px', 
                borderRadius: '24px', 
                background: 'var(--primary-light)', 
                display: 'flex', 
                alignItems: 'center', 
                justifyContent: 'center',
                color: 'var(--primary)'
              }}>
                <Upload size={32} />
              </div>
              <div>
                <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem' }}>Upload</h3>
                <p style={{ color: 'var(--text-secondary)', fontWeight: '600' }}>Medical Report</p>
              </div>
              <div style={{ marginLeft: 'auto', opacity: '0.2' }}>
                <FileText size={48} />
              </div>
            </div>

            <div className="dashboard-card" style={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: '2rem', 
              cursor: 'pointer',
              background: 'var(--bg-surface)'
            }} onClick={() => navigate('/share-access')} id="share-section">
              <div style={{ 
                width: '80px', 
                height: '80px', 
                borderRadius: '24px', 
                background: 'var(--secondary-glow)', 
                display: 'flex', 
                alignItems: 'center', 
                justifyContent: 'center',
                color: 'var(--secondary)'
              }}>
                <QrCode size={32} />
              </div>
              <div>
                <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem' }}>Share</h3>
                <p style={{ color: 'var(--text-secondary)', fontWeight: '600' }}>Access with Doctor</p>
              </div>
              <div style={{ marginLeft: 'auto', opacity: '0.2' }}>
                <PieChart size={48} />
              </div>
            </div>
          </div>

          {/* New Features Sections */}
          <div style={{ marginTop: '3rem', display: 'grid', gridTemplateColumns: 'minmax(0, 2fr) 1fr', gap: '2.5rem' }}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
              <div className="section-title">
                <h3 style={{ fontSize: '1.25rem' }}>Health Insights</h3>
              </div>
              <div className="dashboard-card" style={{ background: 'var(--bg-surface)', position: 'relative', overflow: 'hidden' }}>
                <div style={{ position: 'relative', zIndex: '1' }}>
                  <div style={{ display: 'flex', gap: '1rem', marginBottom: '1.5rem' }}>
                    <div style={{ background: '#ecfdf5', color: '#10b981', padding: '0.5rem 1rem', borderRadius: '100px', fontSize: '0.75rem', fontWeight: '800' }}>BPM: 72</div>
                    <div style={{ background: '#fdf2f8', color: '#db2777', padding: '0.5rem 1rem', borderRadius: '100px', fontSize: '0.75rem', fontWeight: '800' }}>Weight: 68kg</div>
                    <div style={{ background: '#f0f9ff', color: '#0ea5e9', padding: '0.5rem 1rem', borderRadius: '100px', fontSize: '0.75rem', fontWeight: '800' }}>Step Goal: 82%</div>
                  </div>
                  <h4 style={{ fontSize: '1.125rem', marginBottom: '1rem' }}>Great Progress!</h4>
                  <p style={{ color: 'var(--text-secondary)', lineHeight: '1.6', marginBottom: '1.5rem' }}>
                    Your physical activity has increased by 15% this week. Keep up your current routine to maintain your metabolic health targets.
                  </p>
                  <button className="btn btn-secondary" style={{ padding: '0.6rem 1.25rem', fontSize: '0.85rem' }}>View Analytics</button>
                </div>
                <Activity size={120} style={{ position: 'absolute', right: '-20px', bottom: '-20px', opacity: '0.05', transform: 'rotate(-15deg)' }} />
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '1.5rem' }}>
                <div className="dashboard-card" style={{ padding: '2rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1rem' }}>
                    <div style={{ background: '#fef3c7', color: '#d97706', width: '40px', height: '40px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <Activity size={20} />
                    </div>
                    <h4 style={{ fontSize: '1rem' }}>Vitals Tracker</h4>
                  </div>
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>Last checked 2 hours ago.</p>
                  <div style={{ fontSize: '1.5rem', fontWeight: '800', color: 'var(--primary)' }}>120/80 <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>mmHg</span></div>
                </div>

                <div className="dashboard-card" style={{ padding: '2rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', marginBottom: '1rem' }}>
                    <div style={{ background: '#e0f2fe', color: '#0369a1', width: '40px', height: '40px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <Sparkles size={20} />
                    </div>
                    <h4 style={{ fontSize: '1rem' }}>AI Forecast</h4>
                  </div>
                  <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>Wellness prediction for next week.</p>
                  <div style={{ fontSize: '1.25rem', fontWeight: '800', color: '#10b981' }}>High Wellness</div>
                </div>
              </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
              <div className="section-title">
                <h3 style={{ fontSize: '1.25rem' }}>Medical Services</h3>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                {[
                  { label: 'Tele-Consultation', color: '#0066FF', bg: '#E0F2FE' },
                  { label: 'E-Pharmacy', color: '#10B981', bg: '#ECFDF5' },
                  { label: 'Lab Booking', color: '#8B5CF6', bg: '#F5F3FF' },
                  { label: 'Emergency Help', color: '#EF4444', bg: '#FEF2F2' }
                ].map((svc, i) => (
                  <div key={i} className="dashboard-card" style={{ padding: '1.25rem', display: 'flex', alignItems: 'center', gap: '1rem', cursor: 'pointer' }}>
                    <div style={{ background: svc.bg, color: svc.color, width: '44px', height: '44px', borderRadius: '12px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <Activity size={20} />
                    </div>
                    <span style={{ fontWeight: '700', fontSize: '0.95rem' }}>{svc.label}</span>
                    <ChevronRight size={16} style={{ marginLeft: 'auto', opacity: '0.3' }} />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>

      {/* Document Selection for AI Summary */}
      {showSummaryModal && (
        <div className="modal-overlay glass">
          <div className="modal-content glass" style={{ maxWidth: '600px', padding: '3rem', border: '1px solid white' }}>
            <button className="btn-close" onClick={() => setShowSummaryModal(false)} style={{ position: 'absolute', top: '1.5rem', right: '1.5rem' }}>
              <X size={24} />
            </button>
            <div style={{ background: 'var(--primary-light)', color: 'var(--primary)', width: '64px', height: '64px', borderRadius: '16px', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1.5rem' }}>
              <Sparkles size={32} />
            </div>
            <h2 style={{ fontSize: '1.75rem', marginBottom: '0.5rem' }}>Select Document</h2>
            <p className="text-secondary mb-8">Choose a document for AI-powered clinical analysis.</p>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', maxHeight: '400px', overflowY: 'auto', paddingRight: '0.5rem' }}>
              {records.length > 0 ? records.map(record => (
                <div 
                  key={record._id} 
                  onClick={() => handleSummarize(record)}
                  className="glass"
                  style={{ 
                    padding: '1.5rem', 
                    borderRadius: '16px', 
                    cursor: 'pointer', 
                    display: 'flex', 
                    alignItems: 'center', 
                    gap: '1rem',
                    textAlign: 'left',
                    transition: 'all 0.2s ease',
                    border: '1px solid var(--border-color)'
                  }}
                >
                  <div style={{ padding: '10px', borderRadius: '12px', background: 'var(--primary-light)', color: 'var(--primary)' }}>
                    <FileText size={20} />
                  </div>
                  <div style={{ flex: 1 }}>
                    <p style={{ fontWeight: '700', margin: 0 }}>{record.title}</p>
                    <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', margin: 0 }}>{record.category || 'Clinical Document'}</p>
                  </div>
                  <ChevronRight size={18} style={{ opacity: 0.3 }} />
                </div>
              )) : (
                <div style={{ padding: '3rem', textAlign: 'center', color: 'var(--text-muted)' }}>
                  No documents found. Upload a record first.
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* AI Processing / Results Modal */}
      {selectedRecord && (isSummarizing || !isSummarizing) && (
        <div className="modal-overlay glass" style={{ zIndex: 1001 }}>
          <div className="modal-content glass" style={{ maxWidth: '700px', padding: '3.5rem', border: '1px solid white', textAlign: 'left' }}>
            {isSummarizing ? (
              <div style={{ textAlign: 'center', padding: '2rem 0' }}>
                <Activity size={48} className="animate-pulse" style={{ color: 'var(--primary)', marginBottom: '1.5rem' }} />
                <h2 style={{ fontSize: '1.75rem', fontWeight: 800 }}>Analyzing {selectedRecord.category}...</h2>
                <p className="text-secondary">Our clinical engine is extracting vitals and observations.</p>
              </div>
            ) : (
              <>
                <button className="btn-close" onClick={() => setSelectedRecord(null)} style={{ position: 'absolute', top: '1.5rem', right: '1.5rem' }}>
                  <X size={24} />
                </button>
                <div style={{ display: 'flex', alignItems: 'center', gap: '1.5rem', marginBottom: '2.5rem' }}>
                  <div style={{ background: 'var(--primary)', color: 'white', padding: '12px', borderRadius: '14px' }}>
                    <Activity size={24} />
                  </div>
                  <div>
                    <span style={{ fontSize: '0.65rem', fontWeight: '800', background: 'var(--primary-light)', color: 'var(--primary)', padding: '2px 8px', borderRadius: '4px' }}>AI CLINICAL INSIGHT</span>
                    <h2 style={{ fontWeight: 800, fontSize: '1.5rem', margin: 0 }}>{selectedRecord.title} Analysis</h2>
                  </div>
                </div>
                
                <div style={{ background: 'white', borderRadius: '24px', padding: '2.5rem', border: '1px solid var(--border-color)', marginBottom: '2rem' }}>
                  <h4 style={{ fontSize: '1rem', fontWeight: 800, marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <PlusCircle size={18} style={{ color: 'var(--primary)' }} />
                    Key Observations
                  </h4>
                  <p style={{ lineHeight: '1.8', color: 'var(--text-primary)', fontSize: '1.05rem', margin: 0 }}>
                    Based on our AI analysis of your {selectedRecord.category}, the values appear to be within normal clinical ranges. 
                    However, we noticed a slight trend in your recent biochemical markers that suggests increasing your water intake and monitoring salt consumption. 
                    No immediate red flags were detected.
                  </p>
                </div>

                <div style={{ display: 'flex', gap: '1rem' }}>
                   <button onClick={() => setSelectedRecord(null)} className="btn btn-secondary" style={{ flex: 1, height: '56px' }}>Close</button>
                   <button 
                     onClick={() => {
                       window.open(`http://127.0.0.1:5000${selectedRecord.fileUrl}`, '_blank');
                       setSelectedRecord(null);
                     }}
                     className="btn btn-primary" 
                     style={{ flex: 2, height: '56px' }}
                   >
                     View Original Document
                   </button>
                </div>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

// Add standard icon
const ChevronRight = ({ size, style }) => (
  <svg 
    xmlns="http://www.w3.org/2000/svg" 
    width={size} 
    height={size} 
    viewBox="0 0 24 24" 
    fill="none" 
    stroke="currentColor" 
    strokeWidth="2" 
    strokeLinecap="round" 
    strokeLinejoin="round" 
    style={style}
  >
    <path d="m9 18 6-6-6-6"/>
  </svg>
);

export default PatientDashboard;
